---
outputs:
- Reveal
title: Bloguear con R Markdown
hidden: true
layout: list
weight: 1
output: hugodown::md_document
---

# Bloguear con R Markdown

:wave: ¡Hola!

---

Soy Maëlle (Ma-El)! Me gustan R, bloguear y la ciencia.

{{% fragment %}}

:house: https://masalmon.eu

{{% /fragment %}}


---

# ¿Porqué bloguear?

---

* Notas para Ustedes en el futuro

* ¿Les gustan compartir?

* Oportunidades

---

`r hugodown::embed_tweet("1313179237487124486")`

---

Creo que bloguear me dió la oportunidad dar este curso però bloguear no es un esquema de pirámide!

---

# ¿Porqué crear un sitio web?

¿Y si no quiero bloguear a menudo?

<!--html_preserve-->

- {{% fragment %}}Tener una plataforma para compartir cosas cuando lo necessitan.{{% /fragment %}}
- {{% fragment %}}Portfolio. En particular, imaginense a alguién recomonando su nombre para algo.{{% /fragment %}}

<!--/html_preserve-->
---

`r hugodown::embed_tweet("1302774966199504896")`
---

`r hugodown::embed_tweet("1311242386899689472")`

---

# What is a website?

* static: HTML, CSS, JS

* non static: more machinery on the server side

Online server somewhere.

---

# Why Rmd for blogging?

- {{% fragment %}}Data analysis with R{{% /fragment %}}
- {{% fragment %}}Blogging about R{{% /fragment %}}
- {{% fragment %}}R as an utility tool e.g. to generate text from structured data{{% /fragment %}}
- {{% fragment %}}knitr supports other languages...{{% /fragment %}}

---

# WHAT is a scientific Rmd blog?

---

IMHO :smile_cat:

I'll list criteria so we have something to compare our adventures to.

---

# Tech part

<!--html_preserve-->

* {{% fragment %}}Easy way to update from Rmd without too much copy-pasting{{% /fragment %}}

* {{% fragment %}}Fits into your existing workflow or uses things you want to learn and invest time in{{% /fragment %}}

* {{% fragment %}}Code, syntax highlighting{{% /fragment %}}

* {{% fragment %}}Modern tooling (html5? mobile friendly?){{% /fragment %}}

<!--/html_preserve-->
---

# Science part

* {{% fragment %}}References from a .bib file{{% /fragment %}}

* {{% fragment %}}Easy way to cite posts?{{% /fragment %}}

* {{% fragment %}}Equations {{% /fragment %}}

* {{% fragment %}}Content. Blog about science, or stuff relevant to science&co (e.g. comparisons of way to fit and present linear models in R).{{% /fragment %}}

---

# Human part

* {{% fragment %}}Accessible. Alt text, contrast. Don't add gate-keeping to science.{{% /fragment %}}

* {{% fragment %}}You OWN it. Content, URL (no commercial service, no employer).{{% /fragment %}}

* {{% fragment %}}Allows for interactions (social media? commenting?){{% /fragment %}}

* {{% fragment %}}Costs a few dollars a month at most.{{% /fragment %}}

---

# Let's go

* {{% fragment %}}distill{{% /fragment %}}

* {{% fragment %}}Hugo&hugodown{{% /fragment %}}

* {{% fragment %}}Reproducibility{{% /fragment %}}

* {{% fragment %}}Promotion{{% /fragment %}}

* {{% fragment %}}Debrief{{% /fragment %}}

---

# We'll start with a tour of the course website

https://tiny.cc/rmd-blog
