---
outputs:
- Reveal
title: Conclusión
hidden: true
layout: list
weight: 1
output: hugodown::md_document
---

# Bloguear con R Markdown

:sob: ¡Quasi llega la hora de decirse adiós!

---

* distill: perfecto, poco flexibilidad

* Hugo&hugodown: muy (¿demasiado?) flexibilidad, cambios frequentes (però hugodown clava una versión al sitio), hugodown es experimental

* Hugo & blogdown [wishlist de Alison Presmanes Hill](https://github.com/rstudio/blogdown/issues/476)

---

# ¿Qué elegir?

Si no quieren una estructura de sitio muy especial,

* distill

* Hugo Academic with `hugodown::create_site_academic()`

---

# ¿Qué elegir?

¿No hay que decidir immediatamente, jueguen un poco con las einas?

¿Hay alguién que quiere decir lo que eligió/eligiria?

---

# Con todas las einas...

* Lean la documentacion y siguan el desarrollo! :eyes:

* Salvaguarden! :warning:

---

# Cambiar de einas?

* Buscar einas de migración (por ejemplo "from WordPress to Hugo")

* Paquetes `yaml`, `commonmark`, etc.

* Redirects! pagina 404.

---

# ¡diviértanse!

Si tienen miedo publicar entradas, busca un amig@ de R para leer sus borradores.

Haganlo bien però no sean perfectionistas.

---

# Setup no es divertido

* Con paquetes R como distill y hugodown, el setup puede ser más facil.

* Però en general instalar y utilizar cosas nuevas es dificil... por suerte nos acostrumbamos!

---

# Bloguear a menudo

No hay que publicar cada dia. No llamen a su blog "Entradas de R cotidianas" o algo asi. :wink:

---

# Después de mi charla

* Preguntas en el [repositorio del sitio](https://github.com/maelle/rmd-blogging-course/issues)  :raising_hand:

* [Tuits](https://twitter.com/ma_salmon) o correos electronicos para mostrarme su sitio. :star:
